import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Language = 'en' | 'tr' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'zh' | 'ja';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
];

// Translation keys
type TranslationKey = 
  | 'welcome.headline1'
  | 'welcome.headline2'
  | 'welcome.description'
  | 'welcome.feature1.title'
  | 'welcome.feature1.desc'
  | 'welcome.feature2.title'
  | 'welcome.feature2.desc'
  | 'welcome.feature3.title'
  | 'welcome.feature3.desc'
  | 'welcome.startWriting'
  | 'welcome.createAccount'
  | 'welcome.signIn'
  | 'welcome.beginJourney'
  | 'welcome.continueStory'
  | 'welcome.letsWeave'
  | 'welcome.tellUs'
  | 'auth.email'
  | 'auth.password'
  | 'auth.displayName'
  | 'auth.signUp'
  | 'auth.signIn'
  | 'auth.noAccount'
  | 'auth.hasAccount'
  | 'nav.overview'
  | 'nav.outline'
  | 'nav.chapters'
  | 'nav.characters'
  | 'nav.lore'
  | 'nav.map'
  | 'nav.studio'
  | 'nav.settings'
  | 'common.save'
  | 'common.cancel'
  | 'common.delete'
  | 'common.loading'
  | 'common.add'
  | 'common.edit'
  | 'overview.title'
  | 'overview.subtitle'
  | 'overview.narrativeIntent'
  | 'overview.stakes'
  | 'overview.setting'
  | 'overview.timePeriod'
  | 'overview.themes'
  | 'overview.stats'
  | 'overview.wordCount'
  | 'overview.chapters'
  | 'overview.characters'
  | 'map.title'
  | 'map.subtitle'
  | 'map.addNode'
  | 'map.connect'
  | 'map.nodeTypes.chapter'
  | 'map.nodeTypes.character'
  | 'map.nodeTypes.event'
  | 'map.nodeTypes.location'
  | 'settings.title'
  | 'settings.storyDetails'
  | 'settings.storyTitle'
  | 'settings.language'
  | 'settings.tone'
  | 'settings.themes'
  | 'settings.dangerZone'
  | 'settings.deleteStory';

type Translations = Record<Language, Record<TranslationKey, string>>;

const translations: Translations = {
  en: {
    'welcome.headline1': 'Where Stories',
    'welcome.headline2': 'Come Alive',
    'welcome.description': 'An AI-powered narrative canvas that understands your story, generates rich worlds, and adapts its entire interface to match your vision.',
    'welcome.feature1.title': 'Story-First Intelligence',
    'welcome.feature1.desc': 'AI understands your narrative and generates characters, lore, and plot that feel authentic.',
    'welcome.feature2.title': 'Living Theme System',
    'welcome.feature2.desc': 'The interface transforms to match your story\'s genre and mood.',
    'welcome.feature3.title': 'Guided Creation',
    'welcome.feature3.desc': 'From concept to manuscript, with intelligent assistance at every step.',
    'welcome.startWriting': 'Start Writing',
    'welcome.createAccount': 'Create Your Account',
    'welcome.signIn': 'Welcome Back',
    'welcome.beginJourney': 'Begin your storytelling journey',
    'welcome.continueStory': 'Continue your story',
    'welcome.letsWeave': "Let's Weave Your Story",
    'welcome.tellUs': 'Tell us about the world you want to create. The more detail you provide, the richer your story foundation will be.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.displayName': 'Display Name',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'nav.overview': 'Overview',
    'nav.outline': 'Outline',
    'nav.chapters': 'Chapters',
    'nav.characters': 'Characters',
    'nav.lore': 'Lore',
    'nav.map': 'Story Map',
    'nav.studio': 'Writing Studio',
    'nav.settings': 'Settings',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'overview.title': 'Story Overview',
    'overview.subtitle': 'Define the high-level narrative vision',
    'overview.narrativeIntent': 'Narrative Intent',
    'overview.stakes': 'Stakes',
    'overview.setting': 'Setting Description',
    'overview.timePeriod': 'Time Period',
    'overview.themes': 'Central Themes',
    'overview.stats': 'Story Statistics',
    'overview.wordCount': 'Total Words',
    'overview.chapters': 'Chapters',
    'overview.characters': 'Characters',
    'map.title': 'Story Map',
    'map.subtitle': 'Visualize your narrative structure',
    'map.addNode': 'Add Node',
    'map.connect': 'Connect',
    'map.nodeTypes.chapter': 'Chapter',
    'map.nodeTypes.character': 'Character',
    'map.nodeTypes.event': 'Event',
    'map.nodeTypes.location': 'Location',
    'settings.title': 'Settings',
    'settings.storyDetails': 'Story Details',
    'settings.storyTitle': 'Story Title',
    'settings.language': 'Language',
    'settings.tone': 'Tone',
    'settings.themes': 'Theme Colors',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteStory': 'Delete Story',
  },
  tr: {
    'welcome.headline1': 'Hikayelerin',
    'welcome.headline2': 'Canlandığı Yer',
    'welcome.description': 'Hikayenizi anlayan, zengin dünyalar üreten ve arayüzünü vizyonunuza uyarlayan yapay zeka destekli bir anlatı tuvali.',
    'welcome.feature1.title': 'Hikaye Odaklı Zeka',
    'welcome.feature1.desc': 'AI anlatınızı anlayarak özgün hissettiren karakterler, geçmiş ve olay örgüsü üretir.',
    'welcome.feature2.title': 'Canlı Tema Sistemi',
    'welcome.feature2.desc': 'Arayüz, hikayenizin türüne ve ruh haline göre dönüşür.',
    'welcome.feature3.title': 'Rehberli Yaratım',
    'welcome.feature3.desc': 'Konseptten el yazmasına, her adımda akıllı yardım.',
    'welcome.startWriting': 'Yazmaya Başla',
    'welcome.createAccount': 'Hesap Oluştur',
    'welcome.signIn': 'Tekrar Hoş Geldiniz',
    'welcome.beginJourney': 'Hikaye anlatma yolculuğunuza başlayın',
    'welcome.continueStory': 'Hikayenize devam edin',
    'welcome.letsWeave': 'Hikayenizi Örelim',
    'welcome.tellUs': 'Yaratmak istediğiniz dünyayı bize anlatın. Ne kadar çok detay verirseniz, hikaye temeliniz o kadar zengin olur.',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.displayName': 'Görünen Ad',
    'auth.signUp': 'Kayıt Ol',
    'auth.signIn': 'Giriş Yap',
    'auth.noAccount': 'Hesabınız yok mu?',
    'auth.hasAccount': 'Zaten hesabınız var mı?',
    'nav.overview': 'Genel Bakış',
    'nav.outline': 'Taslak',
    'nav.chapters': 'Bölümler',
    'nav.characters': 'Karakterler',
    'nav.lore': 'Gelenek',
    'nav.map': 'Hikaye Haritası',
    'nav.studio': 'Yazı Stüdyosu',
    'nav.settings': 'Ayarlar',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.loading': 'Yükleniyor...',
    'common.add': 'Ekle',
    'common.edit': 'Düzenle',
    'overview.title': 'Hikaye Özeti',
    'overview.subtitle': 'Üst düzey anlatı vizyonunu tanımlayın',
    'overview.narrativeIntent': 'Anlatı Amacı',
    'overview.stakes': 'Riskler',
    'overview.setting': 'Mekan Açıklaması',
    'overview.timePeriod': 'Zaman Dilimi',
    'overview.themes': 'Ana Temalar',
    'overview.stats': 'Hikaye İstatistikleri',
    'overview.wordCount': 'Toplam Kelime',
    'overview.chapters': 'Bölümler',
    'overview.characters': 'Karakterler',
    'map.title': 'Hikaye Haritası',
    'map.subtitle': 'Anlatı yapınızı görselleştirin',
    'map.addNode': 'Düğüm Ekle',
    'map.connect': 'Bağla',
    'map.nodeTypes.chapter': 'Bölüm',
    'map.nodeTypes.character': 'Karakter',
    'map.nodeTypes.event': 'Olay',
    'map.nodeTypes.location': 'Mekan',
    'settings.title': 'Ayarlar',
    'settings.storyDetails': 'Hikaye Detayları',
    'settings.storyTitle': 'Hikaye Başlığı',
    'settings.language': 'Dil',
    'settings.tone': 'Ton',
    'settings.themes': 'Tema Renkleri',
    'settings.dangerZone': 'Tehlikeli Bölge',
    'settings.deleteStory': 'Hikayeyi Sil',
  },
  es: {
    'welcome.headline1': 'Donde las Historias',
    'welcome.headline2': 'Cobran Vida',
    'welcome.description': 'Un lienzo narrativo impulsado por IA que comprende tu historia, genera mundos ricos y adapta toda su interfaz a tu visión.',
    'welcome.feature1.title': 'Inteligencia Narrativa',
    'welcome.feature1.desc': 'La IA comprende tu narrativa y genera personajes, historia y trama auténticos.',
    'welcome.feature2.title': 'Sistema de Temas Vivo',
    'welcome.feature2.desc': 'La interfaz se transforma para coincidir con el género y estado de ánimo de tu historia.',
    'welcome.feature3.title': 'Creación Guiada',
    'welcome.feature3.desc': 'Del concepto al manuscrito, con asistencia inteligente en cada paso.',
    'welcome.startWriting': 'Comenzar a Escribir',
    'welcome.createAccount': 'Crear Tu Cuenta',
    'welcome.signIn': 'Bienvenido de Nuevo',
    'welcome.beginJourney': 'Comienza tu viaje narrativo',
    'welcome.continueStory': 'Continúa tu historia',
    'welcome.letsWeave': 'Tejamos Tu Historia',
    'welcome.tellUs': 'Cuéntanos sobre el mundo que quieres crear. Cuantos más detalles proporciones, más rica será la base de tu historia.',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.displayName': 'Nombre para mostrar',
    'auth.signUp': 'Registrarse',
    'auth.signIn': 'Iniciar Sesión',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'nav.overview': 'Vista General',
    'nav.outline': 'Esquema',
    'nav.chapters': 'Capítulos',
    'nav.characters': 'Personajes',
    'nav.lore': 'Trasfondo',
    'nav.map': 'Mapa de Historia',
    'nav.studio': 'Estudio de Escritura',
    'nav.settings': 'Configuración',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.loading': 'Cargando...',
    'common.add': 'Añadir',
    'common.edit': 'Editar',
    'overview.title': 'Resumen de la Historia',
    'overview.subtitle': 'Define la visión narrativa de alto nivel',
    'overview.narrativeIntent': 'Intención Narrativa',
    'overview.stakes': 'Lo que está en juego',
    'overview.setting': 'Descripción del Escenario',
    'overview.timePeriod': 'Período de Tiempo',
    'overview.themes': 'Temas Centrales',
    'overview.stats': 'Estadísticas de Historia',
    'overview.wordCount': 'Palabras Totales',
    'overview.chapters': 'Capítulos',
    'overview.characters': 'Personajes',
    'map.title': 'Mapa de Historia',
    'map.subtitle': 'Visualiza tu estructura narrativa',
    'map.addNode': 'Añadir Nodo',
    'map.connect': 'Conectar',
    'map.nodeTypes.chapter': 'Capítulo',
    'map.nodeTypes.character': 'Personaje',
    'map.nodeTypes.event': 'Evento',
    'map.nodeTypes.location': 'Ubicación',
    'settings.title': 'Configuración',
    'settings.storyDetails': 'Detalles de la Historia',
    'settings.storyTitle': 'Título de la Historia',
    'settings.language': 'Idioma',
    'settings.tone': 'Tono',
    'settings.themes': 'Colores del Tema',
    'settings.dangerZone': 'Zona de Peligro',
    'settings.deleteStory': 'Eliminar Historia',
  },
  fr: {
    'welcome.headline1': 'Où les Histoires',
    'welcome.headline2': 'Prennent Vie',
    'welcome.description': "Une toile narrative alimentée par l'IA qui comprend votre histoire, génère des mondes riches et adapte toute son interface à votre vision.",
    'welcome.feature1.title': 'Intelligence Narrative',
    'welcome.feature1.desc': "L'IA comprend votre récit et génère des personnages, un lore et une intrigue authentiques.",
    'welcome.feature2.title': 'Système de Thèmes Vivant',
    'welcome.feature2.desc': "L'interface se transforme pour correspondre au genre et à l'ambiance de votre histoire.",
    'welcome.feature3.title': 'Création Guidée',
    'welcome.feature3.desc': 'Du concept au manuscrit, avec une assistance intelligente à chaque étape.',
    'welcome.startWriting': "Commencer à Écrire",
    'welcome.createAccount': 'Créer Votre Compte',
    'welcome.signIn': 'Bon Retour',
    'welcome.beginJourney': 'Commencez votre voyage narratif',
    'welcome.continueStory': 'Continuez votre histoire',
    'welcome.letsWeave': 'Tissons Votre Histoire',
    'welcome.tellUs': "Parlez-nous du monde que vous voulez créer. Plus vous donnez de détails, plus la base de votre histoire sera riche.",
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.displayName': "Nom d'affichage",
    'auth.signUp': "S'inscrire",
    'auth.signIn': 'Se Connecter',
    'auth.noAccount': "Pas de compte ?",
    'auth.hasAccount': 'Déjà un compte ?',
    'nav.overview': 'Aperçu',
    'nav.outline': 'Plan',
    'nav.chapters': 'Chapitres',
    'nav.characters': 'Personnages',
    'nav.lore': 'Lore',
    'nav.map': 'Carte Narrative',
    'nav.studio': "Studio d'Écriture",
    'nav.settings': 'Paramètres',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.loading': 'Chargement...',
    'common.add': 'Ajouter',
    'common.edit': 'Modifier',
    'overview.title': "Aperçu de l'Histoire",
    'overview.subtitle': 'Définissez la vision narrative de haut niveau',
    'overview.narrativeIntent': 'Intention Narrative',
    'overview.stakes': 'Enjeux',
    'overview.setting': 'Description du Cadre',
    'overview.timePeriod': 'Période',
    'overview.themes': 'Thèmes Centraux',
    'overview.stats': "Statistiques de l'Histoire",
    'overview.wordCount': 'Mots Totaux',
    'overview.chapters': 'Chapitres',
    'overview.characters': 'Personnages',
    'map.title': 'Carte Narrative',
    'map.subtitle': 'Visualisez votre structure narrative',
    'map.addNode': 'Ajouter un Nœud',
    'map.connect': 'Connecter',
    'map.nodeTypes.chapter': 'Chapitre',
    'map.nodeTypes.character': 'Personnage',
    'map.nodeTypes.event': 'Événement',
    'map.nodeTypes.location': 'Lieu',
    'settings.title': 'Paramètres',
    'settings.storyDetails': "Détails de l'Histoire",
    'settings.storyTitle': "Titre de l'Histoire",
    'settings.language': 'Langue',
    'settings.tone': 'Ton',
    'settings.themes': 'Couleurs du Thème',
    'settings.dangerZone': 'Zone de Danger',
    'settings.deleteStory': "Supprimer l'Histoire",
  },
  de: {
    'welcome.headline1': 'Wo Geschichten',
    'welcome.headline2': 'Lebendig Werden',
    'welcome.description': 'Eine KI-gestützte Erzählleinwand, die Ihre Geschichte versteht, reiche Welten generiert und ihre gesamte Oberfläche an Ihre Vision anpasst.',
    'welcome.feature1.title': 'Story-First-Intelligenz',
    'welcome.feature1.desc': 'KI versteht Ihre Erzählung und generiert authentische Charaktere, Hintergrund und Handlung.',
    'welcome.feature2.title': 'Lebendiges Themensystem',
    'welcome.feature2.desc': 'Die Oberfläche passt sich dem Genre und der Stimmung Ihrer Geschichte an.',
    'welcome.feature3.title': 'Geführte Kreation',
    'welcome.feature3.desc': 'Vom Konzept zum Manuskript, mit intelligenter Unterstützung bei jedem Schritt.',
    'welcome.startWriting': 'Schreiben Beginnen',
    'welcome.createAccount': 'Konto Erstellen',
    'welcome.signIn': 'Willkommen Zurück',
    'welcome.beginJourney': 'Beginnen Sie Ihre Erzählreise',
    'welcome.continueStory': 'Setzen Sie Ihre Geschichte fort',
    'welcome.letsWeave': 'Lassen Sie uns Ihre Geschichte Weben',
    'welcome.tellUs': 'Erzählen Sie uns von der Welt, die Sie erschaffen möchten. Je mehr Details Sie geben, desto reicher wird Ihre Geschichtsbasis.',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.displayName': 'Anzeigename',
    'auth.signUp': 'Registrieren',
    'auth.signIn': 'Anmelden',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'nav.overview': 'Überblick',
    'nav.outline': 'Gliederung',
    'nav.chapters': 'Kapitel',
    'nav.characters': 'Charaktere',
    'nav.lore': 'Hintergrund',
    'nav.map': 'Story-Karte',
    'nav.studio': 'Schreibstudio',
    'nav.settings': 'Einstellungen',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.loading': 'Laden...',
    'common.add': 'Hinzufügen',
    'common.edit': 'Bearbeiten',
    'overview.title': 'Story-Überblick',
    'overview.subtitle': 'Definieren Sie die übergeordnete Erzählvision',
    'overview.narrativeIntent': 'Erzählabsicht',
    'overview.stakes': 'Was auf dem Spiel steht',
    'overview.setting': 'Settingbeschreibung',
    'overview.timePeriod': 'Zeitraum',
    'overview.themes': 'Zentrale Themen',
    'overview.stats': 'Story-Statistiken',
    'overview.wordCount': 'Gesamtwörter',
    'overview.chapters': 'Kapitel',
    'overview.characters': 'Charaktere',
    'map.title': 'Story-Karte',
    'map.subtitle': 'Visualisieren Sie Ihre Erzählstruktur',
    'map.addNode': 'Knoten Hinzufügen',
    'map.connect': 'Verbinden',
    'map.nodeTypes.chapter': 'Kapitel',
    'map.nodeTypes.character': 'Charakter',
    'map.nodeTypes.event': 'Ereignis',
    'map.nodeTypes.location': 'Ort',
    'settings.title': 'Einstellungen',
    'settings.storyDetails': 'Story-Details',
    'settings.storyTitle': 'Story-Titel',
    'settings.language': 'Sprache',
    'settings.tone': 'Ton',
    'settings.themes': 'Themenfarben',
    'settings.dangerZone': 'Gefahrenzone',
    'settings.deleteStory': 'Story Löschen',
  },
  it: {
    'welcome.headline1': 'Dove le Storie',
    'welcome.headline2': 'Prendono Vita',
    'welcome.description': "Una tela narrativa alimentata dall'IA che comprende la tua storia, genera mondi ricchi e adatta l'intera interfaccia alla tua visione.",
    'welcome.feature1.title': 'Intelligenza Narrativa',
    'welcome.feature1.desc': "L'IA comprende la tua narrativa e genera personaggi, lore e trama autentici.",
    'welcome.feature2.title': 'Sistema di Temi Vivente',
    'welcome.feature2.desc': "L'interfaccia si trasforma per adattarsi al genere e all'umore della tua storia.",
    'welcome.feature3.title': 'Creazione Guidata',
    'welcome.feature3.desc': 'Dal concetto al manoscritto, con assistenza intelligente ad ogni passo.',
    'welcome.startWriting': 'Inizia a Scrivere',
    'welcome.createAccount': 'Crea il Tuo Account',
    'welcome.signIn': 'Bentornato',
    'welcome.beginJourney': 'Inizia il tuo viaggio narrativo',
    'welcome.continueStory': 'Continua la tua storia',
    'welcome.letsWeave': 'Tessiamo la Tua Storia',
    'welcome.tellUs': 'Raccontaci del mondo che vuoi creare. Più dettagli fornisci, più ricca sarà la base della tua storia.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.displayName': 'Nome visualizzato',
    'auth.signUp': 'Registrati',
    'auth.signIn': 'Accedi',
    'auth.noAccount': 'Non hai un account?',
    'auth.hasAccount': 'Hai già un account?',
    'nav.overview': 'Panoramica',
    'nav.outline': 'Schema',
    'nav.chapters': 'Capitoli',
    'nav.characters': 'Personaggi',
    'nav.lore': 'Lore',
    'nav.map': 'Mappa della Storia',
    'nav.studio': 'Studio di Scrittura',
    'nav.settings': 'Impostazioni',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.loading': 'Caricamento...',
    'common.add': 'Aggiungi',
    'common.edit': 'Modifica',
    'overview.title': 'Panoramica della Storia',
    'overview.subtitle': 'Definisci la visione narrativa di alto livello',
    'overview.narrativeIntent': 'Intento Narrativo',
    'overview.stakes': 'Posta in Gioco',
    'overview.setting': 'Descrizione Ambientazione',
    'overview.timePeriod': 'Periodo Temporale',
    'overview.themes': 'Temi Centrali',
    'overview.stats': 'Statistiche Storia',
    'overview.wordCount': 'Parole Totali',
    'overview.chapters': 'Capitoli',
    'overview.characters': 'Personaggi',
    'map.title': 'Mappa della Storia',
    'map.subtitle': 'Visualizza la tua struttura narrativa',
    'map.addNode': 'Aggiungi Nodo',
    'map.connect': 'Connetti',
    'map.nodeTypes.chapter': 'Capitolo',
    'map.nodeTypes.character': 'Personaggio',
    'map.nodeTypes.event': 'Evento',
    'map.nodeTypes.location': 'Luogo',
    'settings.title': 'Impostazioni',
    'settings.storyDetails': 'Dettagli Storia',
    'settings.storyTitle': 'Titolo Storia',
    'settings.language': 'Lingua',
    'settings.tone': 'Tono',
    'settings.themes': 'Colori Tema',
    'settings.dangerZone': 'Zona Pericolosa',
    'settings.deleteStory': 'Elimina Storia',
  },
  pt: {
    'welcome.headline1': 'Onde Histórias',
    'welcome.headline2': 'Ganham Vida',
    'welcome.description': 'Uma tela narrativa alimentada por IA que entende sua história, gera mundos ricos e adapta toda a interface à sua visão.',
    'welcome.feature1.title': 'Inteligência Narrativa',
    'welcome.feature1.desc': 'A IA entende sua narrativa e gera personagens, lore e enredo autênticos.',
    'welcome.feature2.title': 'Sistema de Temas Vivo',
    'welcome.feature2.desc': 'A interface se transforma para combinar com o gênero e humor da sua história.',
    'welcome.feature3.title': 'Criação Guiada',
    'welcome.feature3.desc': 'Do conceito ao manuscrito, com assistência inteligente em cada passo.',
    'welcome.startWriting': 'Começar a Escrever',
    'welcome.createAccount': 'Criar Sua Conta',
    'welcome.signIn': 'Bem-vindo de Volta',
    'welcome.beginJourney': 'Comece sua jornada narrativa',
    'welcome.continueStory': 'Continue sua história',
    'welcome.letsWeave': 'Vamos Tecer Sua História',
    'welcome.tellUs': 'Conte-nos sobre o mundo que você quer criar. Quanto mais detalhes você fornecer, mais rica será a base da sua história.',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.displayName': 'Nome de exibição',
    'auth.signUp': 'Cadastrar',
    'auth.signIn': 'Entrar',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem uma conta?',
    'nav.overview': 'Visão Geral',
    'nav.outline': 'Esboço',
    'nav.chapters': 'Capítulos',
    'nav.characters': 'Personagens',
    'nav.lore': 'Lore',
    'nav.map': 'Mapa da História',
    'nav.studio': 'Estúdio de Escrita',
    'nav.settings': 'Configurações',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.loading': 'Carregando...',
    'common.add': 'Adicionar',
    'common.edit': 'Editar',
    'overview.title': 'Visão Geral da História',
    'overview.subtitle': 'Defina a visão narrativa de alto nível',
    'overview.narrativeIntent': 'Intenção Narrativa',
    'overview.stakes': 'O Que Está em Jogo',
    'overview.setting': 'Descrição do Cenário',
    'overview.timePeriod': 'Período de Tempo',
    'overview.themes': 'Temas Centrais',
    'overview.stats': 'Estatísticas da História',
    'overview.wordCount': 'Total de Palavras',
    'overview.chapters': 'Capítulos',
    'overview.characters': 'Personagens',
    'map.title': 'Mapa da História',
    'map.subtitle': 'Visualize sua estrutura narrativa',
    'map.addNode': 'Adicionar Nó',
    'map.connect': 'Conectar',
    'map.nodeTypes.chapter': 'Capítulo',
    'map.nodeTypes.character': 'Personagem',
    'map.nodeTypes.event': 'Evento',
    'map.nodeTypes.location': 'Local',
    'settings.title': 'Configurações',
    'settings.storyDetails': 'Detalhes da História',
    'settings.storyTitle': 'Título da História',
    'settings.language': 'Idioma',
    'settings.tone': 'Tom',
    'settings.themes': 'Cores do Tema',
    'settings.dangerZone': 'Zona de Perigo',
    'settings.deleteStory': 'Excluir História',
  },
  ru: {
    'welcome.headline1': 'Где Истории',
    'welcome.headline2': 'Оживают',
    'welcome.description': 'Нарративный холст на базе ИИ, который понимает вашу историю, создаёт богатые миры и адаптирует интерфейс к вашему видению.',
    'welcome.feature1.title': 'Нарративный Интеллект',
    'welcome.feature1.desc': 'ИИ понимает ваше повествование и генерирует подлинных персонажей, лор и сюжет.',
    'welcome.feature2.title': 'Живая Система Тем',
    'welcome.feature2.desc': 'Интерфейс трансформируется в соответствии с жанром и настроением вашей истории.',
    'welcome.feature3.title': 'Направляемое Создание',
    'welcome.feature3.desc': 'От концепции до рукописи с интеллектуальной помощью на каждом шагу.',
    'welcome.startWriting': 'Начать Писать',
    'welcome.createAccount': 'Создать Аккаунт',
    'welcome.signIn': 'С Возвращением',
    'welcome.beginJourney': 'Начните своё нарративное путешествие',
    'welcome.continueStory': 'Продолжите свою историю',
    'welcome.letsWeave': 'Давайте Сплетём Вашу Историю',
    'welcome.tellUs': 'Расскажите нам о мире, который хотите создать. Чем больше деталей вы предоставите, тем богаче будет основа вашей истории.',
    'auth.email': 'Эл. почта',
    'auth.password': 'Пароль',
    'auth.displayName': 'Отображаемое имя',
    'auth.signUp': 'Зарегистрироваться',
    'auth.signIn': 'Войти',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'nav.overview': 'Обзор',
    'nav.outline': 'План',
    'nav.chapters': 'Главы',
    'nav.characters': 'Персонажи',
    'nav.lore': 'Лор',
    'nav.map': 'Карта Истории',
    'nav.studio': 'Студия Письма',
    'nav.settings': 'Настройки',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.loading': 'Загрузка...',
    'common.add': 'Добавить',
    'common.edit': 'Редактировать',
    'overview.title': 'Обзор Истории',
    'overview.subtitle': 'Определите высокоуровневое нарративное видение',
    'overview.narrativeIntent': 'Нарративная Цель',
    'overview.stakes': 'Ставки',
    'overview.setting': 'Описание Сеттинга',
    'overview.timePeriod': 'Временной Период',
    'overview.themes': 'Центральные Темы',
    'overview.stats': 'Статистика Истории',
    'overview.wordCount': 'Всего Слов',
    'overview.chapters': 'Главы',
    'overview.characters': 'Персонажи',
    'map.title': 'Карта Истории',
    'map.subtitle': 'Визуализируйте структуру повествования',
    'map.addNode': 'Добавить Узел',
    'map.connect': 'Соединить',
    'map.nodeTypes.chapter': 'Глава',
    'map.nodeTypes.character': 'Персонаж',
    'map.nodeTypes.event': 'Событие',
    'map.nodeTypes.location': 'Место',
    'settings.title': 'Настройки',
    'settings.storyDetails': 'Детали Истории',
    'settings.storyTitle': 'Название Истории',
    'settings.language': 'Язык',
    'settings.tone': 'Тон',
    'settings.themes': 'Цвета Темы',
    'settings.dangerZone': 'Опасная Зона',
    'settings.deleteStory': 'Удалить Историю',
  },
  zh: {
    'welcome.headline1': '故事',
    'welcome.headline2': '栩栩如生',
    'welcome.description': '一个AI驱动的叙事画布，理解您的故事，生成丰富的世界，并使整个界面适应您的愿景。',
    'welcome.feature1.title': '故事优先智能',
    'welcome.feature1.desc': 'AI理解您的叙事，生成真实的角色、传说和情节。',
    'welcome.feature2.title': '动态主题系统',
    'welcome.feature2.desc': '界面会根据您故事的类型和氛围进行转变。',
    'welcome.feature3.title': '引导创作',
    'welcome.feature3.desc': '从概念到手稿，每一步都有智能协助。',
    'welcome.startWriting': '开始写作',
    'welcome.createAccount': '创建账户',
    'welcome.signIn': '欢迎回来',
    'welcome.beginJourney': '开始您的叙事之旅',
    'welcome.continueStory': '继续您的故事',
    'welcome.letsWeave': '让我们编织您的故事',
    'welcome.tellUs': '告诉我们您想创造的世界。您提供的细节越多，您的故事基础就越丰富。',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.displayName': '显示名称',
    'auth.signUp': '注册',
    'auth.signIn': '登录',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'nav.overview': '概述',
    'nav.outline': '大纲',
    'nav.chapters': '章节',
    'nav.characters': '角色',
    'nav.lore': '背景',
    'nav.map': '故事地图',
    'nav.studio': '写作工作室',
    'nav.settings': '设置',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.loading': '加载中...',
    'common.add': '添加',
    'common.edit': '编辑',
    'overview.title': '故事概述',
    'overview.subtitle': '定义高层叙事愿景',
    'overview.narrativeIntent': '叙事意图',
    'overview.stakes': '利害关系',
    'overview.setting': '场景描述',
    'overview.timePeriod': '时间段',
    'overview.themes': '核心主题',
    'overview.stats': '故事统计',
    'overview.wordCount': '总字数',
    'overview.chapters': '章节',
    'overview.characters': '角色',
    'map.title': '故事地图',
    'map.subtitle': '可视化您的叙事结构',
    'map.addNode': '添加节点',
    'map.connect': '连接',
    'map.nodeTypes.chapter': '章节',
    'map.nodeTypes.character': '角色',
    'map.nodeTypes.event': '事件',
    'map.nodeTypes.location': '地点',
    'settings.title': '设置',
    'settings.storyDetails': '故事详情',
    'settings.storyTitle': '故事标题',
    'settings.language': '语言',
    'settings.tone': '基调',
    'settings.themes': '主题颜色',
    'settings.dangerZone': '危险区域',
    'settings.deleteStory': '删除故事',
  },
  ja: {
    'welcome.headline1': '物語が',
    'welcome.headline2': '生き生きと',
    'welcome.description': 'あなたの物語を理解し、豊かな世界を生成し、インターフェース全体をあなたのビジョンに適応させるAI駆動のナラティブキャンバス。',
    'welcome.feature1.title': 'ストーリーファースト知能',
    'welcome.feature1.desc': 'AIがあなたの物語を理解し、本物のキャラクター、伝承、プロットを生成します。',
    'welcome.feature2.title': 'ライブテーマシステム',
    'welcome.feature2.desc': 'インターフェースが物語のジャンルとムードに合わせて変化します。',
    'welcome.feature3.title': 'ガイド付き創作',
    'welcome.feature3.desc': 'コンセプトから原稿まで、あらゆるステップでインテリジェントな支援。',
    'welcome.startWriting': '書き始める',
    'welcome.createAccount': 'アカウント作成',
    'welcome.signIn': 'おかえりなさい',
    'welcome.beginJourney': '物語の旅を始めましょう',
    'welcome.continueStory': '物語を続ける',
    'welcome.letsWeave': 'あなたの物語を紡ぎましょう',
    'welcome.tellUs': '創りたい世界について教えてください。詳細を多く提供するほど、物語の基盤が豊かになります。',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.displayName': '表示名',
    'auth.signUp': '新規登録',
    'auth.signIn': 'ログイン',
    'auth.noAccount': 'アカウントをお持ちでない方',
    'auth.hasAccount': '既にアカウントをお持ちの方',
    'nav.overview': '概要',
    'nav.outline': 'アウトライン',
    'nav.chapters': '章',
    'nav.characters': 'キャラクター',
    'nav.lore': '設定',
    'nav.map': 'ストーリーマップ',
    'nav.studio': '執筆スタジオ',
    'nav.settings': '設定',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.loading': '読み込み中...',
    'common.add': '追加',
    'common.edit': '編集',
    'overview.title': 'ストーリー概要',
    'overview.subtitle': '高レベルのナラティブビジョンを定義',
    'overview.narrativeIntent': 'ナラティブ意図',
    'overview.stakes': '賭けられているもの',
    'overview.setting': '設定の説明',
    'overview.timePeriod': '時代',
    'overview.themes': '中心テーマ',
    'overview.stats': 'ストーリー統計',
    'overview.wordCount': '総語数',
    'overview.chapters': '章',
    'overview.characters': 'キャラクター',
    'map.title': 'ストーリーマップ',
    'map.subtitle': 'ナラティブ構造を視覚化',
    'map.addNode': 'ノード追加',
    'map.connect': '接続',
    'map.nodeTypes.chapter': '章',
    'map.nodeTypes.character': 'キャラクター',
    'map.nodeTypes.event': 'イベント',
    'map.nodeTypes.location': '場所',
    'settings.title': '設定',
    'settings.storyDetails': 'ストーリー詳細',
    'settings.storyTitle': 'ストーリータイトル',
    'settings.language': '言語',
    'settings.tone': 'トーン',
    'settings.themes': 'テーマカラー',
    'settings.dangerZone': '危険ゾーン',
    'settings.deleteStory': 'ストーリーを削除',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  languages: LanguageInfo[];
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('ui-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('ui-language', lang);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  }, [language]);

  const currentLanguage = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: LANGUAGES, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
